import React,{useMemo,useState}from"react";
import{ScrollView,View,Text,Image,Pressable,TextInput,StyleSheet}from"react-native";
import{demoProducts,formatGs,cartTotal,Product,CartItem}from"@animalife/domain";

const tabs:[string,string][]=[["all","Todos"],["dogs","Perros/Gatos"],["cattle","Bovinos"],["horses","Equinos"],["field","Campo"],["veterinary","Veterinario"]];
export default function Home(){
 const[q,setQ]=useState(""),[cat,setCat]=useState("all"),[cart,setCart]=useState<CartItem[]>([]),[detail,setDetail]=useState<Product|null>(null);
 const list=useMemo(()=>demoProducts.filter(p=>(cat==="all"||p.category===cat)&&(p.name.toLowerCase().includes(q.toLowerCase())||p.brand.toLowerCase().includes(q.toLowerCase()))),[q,cat]);
 const add=(p:Product)=>setCart(c=>{const e=c.find(i=>i.product.id===p.id);return e?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]});
 const count=cart.reduce((a,i)=>a+i.quantity,0);
 if(detail)return <View style={s.root}><Pressable onPress={()=>setDetail(null)}><Text style={s.back}>‹ Volver al catálogo</Text></Pressable><ScrollView><Image source={{uri:detail.image}} style={s.detailImg}/><View style={s.body}><Text style={s.cat}>{detail.categoryLabel}</Text><Text style={s.h1}>{detail.name}</Text><Text style={s.subtitle}>{detail.subtitle}</Text><Text style={s.desc}>{detail.description}</Text>{detail.features?.map(x=><Text key={x} style={s.feature}>✓ {x}</Text>)}<Text style={s.price}>{formatGs(detail.priceGs)}</Text><Pressable style={s.primary}onPress={()=>{add(detail);setDetail(null)}}><Text style={s.primaryText}>Agregar al carrito</Text></Pressable></View></ScrollView></View>;
 return <View style={s.root}><View style={s.head}><View><Text style={s.logo}>ANIMALIFE</Text><Text style={s.py}>AGROVETERINARIA</Text></View><View style={s.badgeCart}><Text style={s.badgeCartText}>{count}</Text></View></View><ScrollView><View style={s.hero}><Text style={s.eyebrow}>PRODUCTOS VETERINARIOS DE CALIDAD</Text><Text style={s.h1}>Todo para el <Text style={s.em}>bienestar animal</Text> y el campo.</Text><Text style={s.desc}>Perros, gatos, bovinos, equinos y soluciones para el campo.</Text></View><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput placeholder="Buscar productos..." value={q} onChangeText={setQ} style={{flex:1,fontSize:14}}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.tabs}>{tabs.map(([id,label])=><Pressable key={id}style={[s.tab,cat===id&&s.tabActive]}onPress={()=>setCat(id)}><Text style={[s.tabText,cat===id&&s.tabTextActive]}>{label}</Text></Pressable>)}</ScrollView><View style={s.grid}>{list.map(p=><Pressable key={p.id} style={s.card} onPress={()=>setDetail(p)}><Image source={{uri:p.image}} style={s.img}/><View style={s.cardBody}><Text style={s.cat}>{p.categoryLabel}</Text><Text style={s.name}>{p.name}</Text><Text style={s.subtitle}>{p.subtitle}</Text><View style={s.buy}><Text style={s.priceSmall}>{formatGs(p.priceGs)}</Text><Pressable onPress={()=>add(p)} style={s.add}><Text style={s.addText}>+</Text></Pressable></View></View></Pressable>)}</View>{cart.length>0&&<View style={s.cartBar}><View><Text style={s.cartText}>{count} producto(s)</Text><Text style={s.cartTotal}>{formatGs(cartTotal(cart))}</Text></View><Pressable style={s.primarySmall}><Text style={s.primaryText}>Ver carrito</Text></Pressable></View>}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f8f7f2",paddingTop:54},head:{paddingHorizontal:20,paddingBottom:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"#fff"},logo:{fontWeight:"900",letterSpacing:2,fontSize:18,color:"#23382b"},py:{fontSize:8,letterSpacing:2,color:"#758078"},badgeCart:{width:36,height:36,borderRadius:18,backgroundColor:"#23382b",alignItems:"center",justifyContent:"center"},badgeCartText:{color:"#fff",fontWeight:"900"},hero:{padding:28},eyebrow:{fontSize:10,letterSpacing:2,color:"#72806f",fontWeight:"800"},h1:{fontSize:39,lineHeight:42,fontWeight:"800",color:"#24372a",marginTop:9},em:{color:"#9c5c30"},desc:{fontSize:14,lineHeight:22,color:"#68736b",marginTop:15},search:{marginHorizontal:20,marginBottom:12,backgroundColor:"#fff",borderRadius:999,paddingHorizontal:15,paddingVertical:10,flexDirection:"row",gap:8,alignItems:"center",borderWidth:1,borderColor:"#e5e8e2"},searchIcon:{fontSize:18,color:"#748078"},tabs:{paddingHorizontal:20,marginBottom:10},tab:{paddingHorizontal:14,paddingVertical:9,borderRadius:30,borderWidth:1,borderColor:"#dfe3dc",marginRight:8,backgroundColor:"#fff"},tabActive:{backgroundColor:"#23382b",borderColor:"#23382b"},tabText:{color:"#5e695f",fontSize:12},tabTextActive:{color:"#fff",fontWeight:"700"},grid:{padding:20,flexDirection:"row",flexWrap:"wrap",gap:12},card:{width:"48%",backgroundColor:"#fff",borderRadius:15,overflow:"hidden",borderWidth:1,borderColor:"#e5e8e2"},img:{width:"100%",height:155},cardBody:{padding:12},cat:{fontSize:9,textTransform:"uppercase",letterSpacing:1.5,fontWeight:"800",color:"#8a948b"},name:{fontWeight:"700",fontSize:15,color:"#27342b",marginTop:4,minHeight:38},subtitle:{fontSize:11,color:"#758078",marginTop:5},buy:{marginTop:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},priceSmall:{fontWeight:"800",fontSize:12,color:"#24372a",flex:1},add:{width:32,height:32,borderRadius:16,backgroundColor:"#23382b",alignItems:"center",justifyContent:"center"},addText:{fontSize:23,lineHeight:24,color:"#fff",fontWeight:"300"},cartBar:{position:"absolute",left:15,right:15,bottom:18,borderRadius:18,backgroundColor:"#fff",padding:13,flexDirection:"row",alignItems:"center",justifyContent:"space-between",shadowColor:"#000",shadowOpacity:.12,shadowRadius:12,elevation:8},cartText:{fontSize:11,color:"#6f7a72"},cartTotal:{fontWeight:"800",color:"#24372a",marginTop:2},primary:{backgroundColor:"#23382b",borderRadius:999,padding:15,alignItems:"center",marginTop:20},primarySmall:{backgroundColor:"#23382b",borderRadius:999,paddingHorizontal:17,paddingVertical:11},primaryText:{color:"#fff",fontWeight:"800"},detailImg:{width:"100%",height:340},back:{padding:16,color:"#23382b",fontWeight:"700"},body:{padding:22},price:{fontSize:24,fontWeight:"900",color:"#24372a",marginTop:20},feature:{fontSize:13,color:"#425047",marginTop:8}})