"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "../../../lib/supabase-browser";
import SiteHeader from "../../../components/SiteHeader";
import SiteFooter from "../../../components/SiteFooter";
const statuses=["CREATED","PAYMENT_PENDING","PAID","PROCESSING","SHIPPED","DELIVERED","CANCELLED","REFUNDED"];
export default function AdminOrders(){const [rows,setRows]=useState<any[]>([]);const [message,setMessage]=useState("");useEffect(()=>{(async()=>{const s=createClient();if(!s)return;const {data:{user}}=await s.auth.getUser();if(!user){setMessage("Inicia sesión como administrador.");return}const {data:p}=await s.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="ADMIN"){setMessage("Acceso restringido.");return}const {data,error}=await s.from("orders").select("id,order_number,email,phone,status,total_pyg,delivery_pyg,created_at,shipping_address").order("created_at",{ascending:false});if(error)setMessage(error.message);else setRows(data??[])})()},[]);
 async function change(id:string,status:string){const s=createClient();if(!s)return;const {error}=await s.from("orders").update({status}).eq("id",id);setMessage(error?error.message:"Estado actualizado.");if(!error)setRows(rs=>rs.map(r=>r.id===id?{...r,status}:r))}
 return <main><SiteHeader/><div className="container admin"><div className="breadcrumbs"><Link href="/admin">Admin</Link> / Pedidos</div><div className="admin-table-head"><div><span className="eyebrow">OPERACIONES</span><h1>Pedidos</h1></div><Link className="btn btn-light" href="/admin">← Dashboard</Link></div>{message&&<p className="notice">{message}</p>}<div className="admin-table"><div className="admin-order-head"><span>Pedido</span><span>Cliente</span><span>Total</span><span>Estado</span></div>{rows.map(x=><div className="admin-order-row" key={x.id}><div><b>{x.order_number}</b><small>{new Date(x.created_at).toLocaleString("es-PY")}</small></div><span>{x.email}<small>{x.phone}</small></span><strong>Gs. {Number(x.total_pyg).toLocaleString("es-PY")}</strong><select value={x.status} onChange={e=>change(x.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>)}</div></div><SiteFooter/></main>}