import Link from "next/link";
import {formatPYG} from "@animalife/shared";
import {getCatalogCategories,getCatalogProducts} from "../lib/catalog-server";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

const categoryImages:Record<string,string>={
  Perros:"https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85",
  Gatos:"https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85",
  Bovinos:"https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=900&q=85",
  Equinos:"https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?auto=format&fit=crop&w=900&q=85",
  Campo:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=85"
};
const heroImage="https://images.unsplash.com/photo-1546447147-3fc2b5c9aa3f?auto=format&fit=crop&w=1500&q=88";
function ProductArt({product}:{product:any}){return <div className="product-art">{product.image?<img src={product.image} alt=""/>:<div className="product-placeholder">{product.animal==="BOVINOS"?"🐄":product.animal==="EQUINOS"?"🐎":product.animal==="CAMPO"?"🌿":product.animal==="GATOS"?"🐈":"🐕"}</div>}</div>}
export default async function Home(){const [categories,products]=await Promise.all([getCatalogCategories(),getCatalogProducts()]);const featured=products.filter(p=>p.featured).slice(0,4);return <main><SiteHeader/>
<section className="hero-premium"><div className="container"><div className="hero-panel"><div className="hero-copy"><span className="eyebrow">ANIMALIFE AGROVETERINARIA · PARAGUAY</span><h1>Todo para el <em>bienestar animal</em> y el campo.</h1><p>Productos veterinarios, alimentos y soluciones seleccionadas para cuidar cada etapa con confianza.</p><div style={{display:"flex",gap:10,marginTop:28}}><Link className="btn btn-lime" href="/catalog">Comprar ahora →</Link><Link className="btn btn-light" href="/catalog">Ver catálogo</Link></div></div><div className="hero-visual"><img src={heroImage} alt="Animales y campo"/><div className="hero-overlay"></div><div className="hero-badge">Calidad · Confianza · Servicio</div></div></div></div></section>
<section className="trust-strip"><div className="container trust-grid"><div className="trust-item"><span className="trust-icon">▣</span><div><b>Envíos a todo Paraguay</b><span>Entrega coordinada</span></div></div><div className="trust-item"><span className="trust-icon">✓</span><div><b>Productos originales</b><span>Selección de calidad</span></div></div><div className="trust-item"><span className="trust-icon">♧</span><div><b>Asesoramiento veterinario</b><span>Atención por WhatsApp</span></div></div><div className="trust-item"><span className="trust-icon">▤</span><div><b>Precios competitivos</b><span>Para profesionales y hogares</span></div></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">EXPLORA</span><h2>Compra por categoría</h2></div><Link href="/catalog">Ver todo →</Link></div><div className="category-showcase">{categories.filter(c=>c.name!=="Ofertas").slice(0,5).map(c=><Link className="category-tile" style={{backgroundImage:`url(${categoryImages[c.name]||""})`}} href={"/catalog?category="+encodeURIComponent(c.name)} key={c.slug}><div className="tile-copy"><b>{c.name}</b><small>Ver productos →</small></div></Link>)}</div></div></section>
<section className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">SELECCIÓN ANIMALIFE</span><h2>Destacados</h2></div><Link href="/catalog">Ver catálogo →</Link></div><div className="product-grid">{featured.map(p=><Link className="product-card" href={"/product/"+p.slug} key={p.id}><ProductArt product={p}/><div className="product-info"><span className="tag">{p.verified&&p.stock>0?"Disponible":"Por verificar"}</span><h3>{p.name}</h3><small>{p.brand??p.category} · {p.packageSize??"Presentación por confirmar"}</small><strong>{p.price>0?formatPYG(p.salePrice??p.price):"Precio a confirmar"}</strong></div></Link>)}</div></div></section>
<section className="section"><div className="container"><div className="promo-grid"><div className="promo dark"><span className="eyebrow" style={{color:"#c6f36a"}}>PARA PROFESIONALES</span><h3>Soluciones para tu negocio veterinario</h3><p>Una selección pensada para veterinarias, productores y profesionales del campo.</p><Link className="btn btn-lime" href="/catalog">Explorar catálogo</Link></div><div className="promo lime"><span className="eyebrow">CAMPO</span><h3>Todo para el productor</h3><p>Productos para bovinos, equinos y campo.</p><Link href="/catalog?category=Campo" className="btn btn-green">Ver productos</Link></div><div className="promo"><span className="eyebrow">ATENCIÓN</span><h3>Estamos para ayudarte</h3><p>Consulta disponibilidad, entregas y productos.</p><Link href="/account" className="btn btn-green">Contactar</Link></div></div></div></section>
<SiteFooter/></main>}