export type ProductCategory="dogs"|"cats"|"cattle"|"horses"|"field"|"veterinary";
export type PaymentMethod="card"|"bank_transfer"|"qr";
export type DeliveryMethod="standard"|"express";
export type Product={id:string;slug:string;name:string;category:ProductCategory;categoryLabel:string;brand:string;subtitle:string;description:string;priceGs:number;compareAtPriceGs?:number;image:string;badge?:string;stock:number;features?:string[]};
export type CartItem={product:Product;quantity:number};
export type Customer={id:string;name:string;email:string;phone?:string};
export type OrderStatus="pending"|"paid"|"processing"|"shipped"|"delivered";
export type Order={id:string;customerId:string;items:CartItem[];subtotalGs:number;shippingGs:number;totalGs:number;status:OrderStatus;paymentMethod:PaymentMethod;deliveryMethod:DeliveryMethod;shippingLabel:string;createdAt:string};
export const formatGs=(v:number)=>new Intl.NumberFormat("es-PY").format(v)+" Gs.";
export const cartTotal=(items:CartItem[])=>items.reduce((s,i)=>s+i.product.priceGs*i.quantity,0);
const I=(u:string)=>u;
export const demoProducts:Product[]=[
{id:"AL-RP-I",slug:"raguife-prime-combo-inicial",name:"Raguife Prime Combo Inicial",category:"dogs",categoryLabel:"Perros/Gatos",brand:"Raguife Prime",subtitle:"27 bolsas • 9 productos",description:"Combo emprendedor Raguife Prime para tu negocio veterinario o pet shop. Incluye 27 bolsas y 9 productos para perros y gatos.",priceGs:1000000,image:I("https://images.unsplash.com/photo-1589924691106-073b2d7c4c0f?auto=format&fit=crop&w=900&q=80"),badge:"Combo",stock:10,features:["Alimento para perros y gatos","Variedad de presentaciones","Ideal para pet shops y veterinarias"]},
{id:"AL-RP-C",slug:"raguife-prime-combo-crecimiento",name:"Raguife Prime Combo Crecimiento",category:"dogs",categoryLabel:"Perros/Gatos",brand:"Raguife Prime",subtitle:"41 bolsas • 9 productos",description:"Combo completo Raguife Prime para emprendedores. Incluye 41 bolsas y 9 productos para perros y gatos. Nutrición premium especial, ideal para tu negocio.",priceGs:1500000,image:I("/products/raguife-prime-combo-crecimiento.jpg"),badge:"Más vendido",stock:8,features:["Alimento para perros adultos y cachorros","Alimento para gatos adultos y gatitos","Variedad de sabores y presentaciones","Ideal para pet shops y veterinarias"]},
{id:"AL-FLU",slug:"fluralab-bovinos-5",name:"Fluralab Bovinos 5%",category:"cattle",categoryLabel:"Bovinos",brand:"Fluralab",subtitle:"Fluralaner 1 L",description:"Control efectivo de parásitos. Presentación de 1 litro.",priceGs:669999,image:I("https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=900&q=80"),stock:14},
{id:"AL-RAN",slug:"ranger-75-7-sg",name:"Ranger 75,7 SG",category:"field",categoryLabel:"Campo",brand:"Ranger",subtitle:"Herbicida 10 kg",description:"Herbicida para manejo de campo. Presentación de 10 kg.",priceGs:400000,image:I("https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80"),stock:18},
{id:"AL-CIP",slug:"cipermetrina-6-calbos",name:"Cipermetrina 6%",category:"cattle",categoryLabel:"Bovinos",brand:"Calbos",subtitle:"Pour-on 1 L",description:"Cipermetrina 6% Calbos Pour-on. Presentación de 1 litro.",priceGs:65000,image:I("https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=900&q=80"),stock:23},
{id:"AL-HIP",slug:"hipofen-pasta-oral",name:"Hipofen Pasta oral",category:"horses",categoryLabel:"Equinos",brand:"Hipofen",subtitle:"Pasta oral 20 g",description:"Pasta oral para equinos en presentación de 20 g.",priceGs:52500,image:I("https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=900&q=80"),stock:30},
{id:"AL-CID",slug:"cidental-veterinario",name:"Cidental",category:"veterinary",categoryLabel:"Veterinario",brand:"Cidental",subtitle:"Uso veterinario 250 ml",description:"Producto de uso veterinario. Presentación de 250 ml.",priceGs:45000,image:I("https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=80"),stock:16},
{id:"AL-ALM",slug:"alambre-morlan-17-15",name:"Alambre Morlan 17/15",category:"field",categoryLabel:"Campo",brand:"Morlan",subtitle:"Rollo 1.000 m",description:"Alambre para cercas y trabajo de campo. Rollo de 1.000 metros.",priceGs:570000,image:I("https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=900&q=80"),stock:9}
];
export interface PaymentProvider{id:string;name:string;createPayment(input:{orderId:string;amountGs:number;method:PaymentMethod}):Promise<{providerPaymentId:string;status:"pending"|"paid"}>}
export interface DeliveryProvider{id:string;name:string;quote(input:{department:string;city:string;method:DeliveryMethod}):Promise<{priceGs:number;etaDays:number}>;createShipment(input:{orderId:string;address:string;method:DeliveryMethod}):Promise<{trackingId:string}>}
export const mockPaymentProvider:PaymentProvider={id:"mock-paraguay",name:"Mock Paraguay Payment",async createPayment({orderId}){return{providerPaymentId:"mock-pay-"+orderId,status:"pending"}}};
export const mockDeliveryProvider:DeliveryProvider={id:"mock-delivery-paraguay",name:"Mock Delivery Paraguay",async quote({method}){return method==="express"?{priceGs:50000,etaDays:1}:{priceGs:30000,etaDays:3}},async createShipment({orderId}){return{trackingId:"AL-"+orderId.toUpperCase()}}};