import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Heart,ShoppingCart,Search,Truck,ShieldCheck,ChevronRight,Plus,Minus,Package,UserCircle,Settings,Lock,CheckCircle}from"lucide-react";
import{demoProducts,formatGs,cartTotal,Product,CartItem,Order,PaymentMethod,DeliveryMethod}from"@animalife/domain";
import"./styles.css";

const cats:[string,string][]=[["all","Todos"],["dogs","Perros/Gatos"],["cattle","Bovinos"],["horses","Equinos"],["field","Campo"],["veterinary","Veterinario"]];
const paymentLabels:[PaymentMethod,string][]=[["card","Tarjeta de crédito o débito"],["bank_transfer","Transferencia bancaria"],["qr","Pago por QR"]];
const deliveryLabels:[DeliveryMethod,string][]=[["standard","Envío estándar"],["express","Envío express"]];

function App(){
 const[category,setCategory]=useState("all"),[query,setQuery]=useState(""),[cart,setCart]=useState<CartItem[]>([]),[selected,setSelected]=useState<Product|null>(null),[panel,setPanel]=useState<"none"|"cart"|"checkout"|"account"|"admin">("none"),[orders,setOrders]=useState<Order[]>([]),[payment,setPayment]=useState<PaymentMethod>("card"),[delivery,setDelivery]=useState<DeliveryMethod>("standard");
 const filtered=useMemo(()=>demoProducts.filter(p=>(category==="all"||p.category===category)&&(p.name.toLowerCase().includes(query.toLowerCase())||p.description.toLowerCase().includes(query.toLowerCase())||p.brand.toLowerCase().includes(query.toLowerCase()))),[category,query]);
 const add=(p:Product)=>setCart(c=>{const e=c.find(i=>i.product.id===p.id);return e?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]});
 const qty=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.product.id!==id?i:[{product:i.product,quantity:Math.max(0,i.quantity+d)}]).filter(i=>i.quantity>0));
 const total=cartTotal(cart),shipping=delivery==="express"?50000:30000,totalWithShipping=total+shipping,count=cart.reduce((s,i)=>s+i.quantity,0);
 const goHome=()=>{setSelected(null);setPanel("none")};
 const createOrder=()=>{const id="AL-2026-"+Date.now().toString().slice(-6);const o:Order={id,customerId:"demo",items:cart,subtotalGs:total,shippingGs:shipping,totalGs:totalWithShipping,status:"pending",paymentMethod:payment,deliveryMethod:delivery,shippingLabel:delivery==="express"?"Express · 24 horas (según zona)":"Estándar · 1–3 días hábiles",createdAt:new Date().toISOString()};setOrders(prev=>[o,...prev]);setCart([]);setPanel("account")};
 return <div className="app">
  <header><div className="logo"onClick={goHome}><span>ANIMALIFE</span><small>AGROVETERINARIA</small></div><div className="search"><Search size={18}/><input placeholder="Buscar productos..."value={query}onChange={e=>setQuery(e.target.value)}/></div><nav><button className="account"onClick={()=>setPanel("account")}><UserCircle size={20}/><span>Mi cuenta</span></button><button className="cartBtn"onClick={()=>setPanel("cart")}><ShoppingCart size={20}/><b>{count}</b><span>Carrito</span></button></nav></header>
  <section className="hero"><div><p className="eyebrow">Productos veterinarios de calidad</p><h1>Todo para el<br/><em>bienestar animal</em><br/>y el campo.</h1><p className="sub">Alimentos, productos veterinarios y soluciones para perros, gatos, bovinos, equinos y el campo.</p><button className="primary"onClick={()=>document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})}>Ver productos <ChevronRight size={18}/></button></div><div className="heroPhoto"><img src="https://images.unsplash.com/photo-1490457843367-34b21b6ccd4f?auto=format&fit=crop&w=1100&q=85"alt="Animales"/></div></section>
  <div className="benefits"><div><Truck/><span><b>Envíos a todo Paraguay</b><small>1–3 días hábiles</small></span></div><div><ShieldCheck/><span><b>Productos originales</b><small>Garantía de calidad</small></span></div><div><Package/><span><b>Asesoramiento</b><small>Atención preparada para WhatsApp</small></span></div></div>
  <main id="catalogo"><div className="sectionHead"><div><p className="eyebrow">Tienda Animalife</p><h2>Todos los productos</h2></div><button className="adminToggle"onClick={()=>setPanel("admin")}><Settings size={16}/> Administración</button></div>
   <div className="tabs">{cats.map(([id,label])=><button key={id}className={category===id?"active":""}onClick={()=>setCategory(id)}>{label}</button>)}</div>
   <div className="grid">{filtered.map(p=><article key={p.id}className="card"><div className="imageWrap"onClick={()=>setSelected(p)}><img src={p.image}alt={p.name}/>{p.badge&&<span className="badge">{p.badge}</span>}<button className="heart"onClick={e=>e.stopPropagation()}><Heart size={17}/></button></div><div className="cardBody"><p className="cat">{p.categoryLabel}</p><h3>{p.name}</h3><p className="desc">{p.subtitle}<br/>{p.description}</p><div className="buyRow"><strong>{formatGs(p.priceGs)}</strong><button onClick={()=>add(p)}aria-label="Agregar"><Plus size={18}/></button></div></div></article>)}</div>
  </main>
  <footer><div><b>ANIMALIFE AGROVETERINARIA</b><span>Paraguay · Bienestar animal y soluciones para el campo</span></div><div><span>Pagos locales preparados</span><span>Envíos preparados para Paraguay</span></div></footer>

  {selected&&<div className="overlay"onClick={()=>setSelected(null)}><div className="modal productModal"onClick={e=>e.stopPropagation()}><img src={selected.image}alt={selected.name}/><div><button className="close"onClick={()=>setSelected(null)}>×</button><p className="cat">{selected.categoryLabel}</p><h2>{selected.name}</h2><p className="subtitle">{selected.subtitle}</p><p>{selected.description}</p>{selected.features&&<div className="featureBox"><b>El producto incluye:</b>{selected.features.map(f=><span key={f}>✓ {f}</span>)}</div>}<div className="bigPrice">{formatGs(selected.priceGs)}</div><div className="stock">{selected.stock} unidades disponibles</div><button className="primary full"onClick={()=>{add(selected);setSelected(null)}}><ShoppingCart size={17}/> Agregar al carrito</button></div></div></div>}

  {panel==="cart"&&<div className="overlay"><div className="modal cartModal"><button className="close"onClick={()=>setPanel("none")}/><h2>Tu carrito de compras</h2>{!cart.length?<div className="empty">Aún no hay productos en tu carrito.</div>:<><div>{cart.map(i=><div className="cartLine"key={i.product.id}><img src={i.product.image}alt=""/><div><b>{i.product.name}</b><span>{i.product.subtitle}</span><strong>{formatGs(i.product.priceGs)}</strong><div className="qty"><button onClick={()=>qty(i.product.id,-1)}><Minus size={14}/></button>{i.quantity}<button onClick={()=>qty(i.product.id,1)}><Plus size={14}/></button></div></div><b>{formatGs(i.product.priceGs*i.quantity)}</b></div>)}</div><div className="shippingNote"><Truck size={19}/><span><b>Envío a todo Paraguay</b><small>Rapidez y seguridad en tus pedidos.</small></span></div><div className="summary"><div><span>Subtotal</span><b>{formatGs(total)}</b></div><div><span>Envío</span><b>{formatGs(30000)}</b></div><div className="grand"><span>Total</span><b>{formatGs(total+30000)}</b></div></div><button className="primary full"onClick={()=>setPanel("checkout")}>Continuar con el pago <ChevronRight size={17}/></button></>}</div></div>}

  {panel==="checkout"&&<div className="overlay"><div className="modal checkout"><button className="close"onClick={()=>setPanel("none")}>×</button><p className="eyebrow">Finalizar compra</p><h2>Datos de entrega</h2><div className="formGrid"><label>Nombre completo<input placeholder="María López"/></label><label>Teléfono<input placeholder="(0981) 123 456"/></label><label>Email<input placeholder="maria.lopez@gmail.com"/></label><label>Departamento<input placeholder="Central"/></label><label>Ciudad<input placeholder="Luque"/></label><label>Dirección<input placeholder="Av. General Aquino 1234"/></label></div><label>Referencia (opcional)<input placeholder="Casa color blanco, portón negro"/></label><h3>3. Método de envío</h3>{deliveryLabels.map(([id,label])=><button key={id}className={"option "+(delivery===id?"selected":"")}onClick={()=>setDelivery(id)}><span><b>{label}</b><small>{id==="standard"?"1–3 días hábiles":"24 horas (según zona)"}</small></span><strong>{formatGs(id==="standard"?30000:50000)}</strong></button>)}<h3>4. Método de pago</h3>{paymentLabels.map(([id,label])=><button key={id}className={"option "+(payment===id?"selected":"")}onClick={()=>setPayment(id)}><span><b>{label}</b><small>{id==="card"?"Pago online seguro":id==="bank_transfer"?"Confirmación manual":"A través de tu billetera"}</small></span>{payment===id&&<CheckCircle size={18}/>}</button>)}<div className="total"><span>Total a pagar</span><b>{formatGs(totalWithShipping)}</b></div><button className="primary full"onClick={createOrder}><Lock size={16}/> Confirmar pedido</button><small className="notice">Modo prototipo: no se realiza ningún cobro real.</small></div></div>}

  {panel==="account"&&<div className="overlay"><div className="modal cartModal"><button className="close"onClick={()=>setPanel("none")}>×</button><p className="eyebrow">Mi cuenta</p><h2>Hola, cliente</h2><div className="accountCard"><UserCircle size={30}/><div><b>Cuenta demo</b><span>Preparada para autenticación y perfiles reales.</span></div></div><h3>Mis pedidos</h3>{orders.length?orders.map(o=><div className="order"key={o.id}><div><b>#{o.id}</b><span>{new Date(o.createdAt).toLocaleDateString("es-PY")} · {o.shippingLabel}</span></div><strong>{formatGs(o.totalGs)}</strong><small>{o.status}</small></div>):<div className="empty">Todavía no hay pedidos.</div>}</div></div>}

  {panel==="admin"&&<div className="overlay"><div className="modal cartModal"><button className="close"onClick={()=>setPanel("none")}>×</button><p className="eyebrow">Back office</p><h2>Gestión de productos</h2><div className="adminPanel"><b>{demoProducts.length} productos de referencia</b><span>Precio · stock · categoría · contenido</span><button className="secondary">+ Nuevo producto</button></div>{demoProducts.map(p=><div className="adminRow"key={p.id}><img src={p.image}alt=""/><div><b>{p.name}</b><span>{p.categoryLabel} · {formatGs(p.priceGs)} · stock {p.stock}</span></div><button className="secondary">Editar</button></div>)}</div></div>}
 </div>
}
createRoot(document.getElementById("root")!).render(<App/>);