import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Heart,ShoppingCart,Search,Truck,ShieldCheck,ChevronRight,Plus,Minus,Package,UserCircle,Settings,ArrowLeft}from"lucide-react";
import{demoProducts,formatGs,cartTotal,Product,CartItem,Order}from"@animalife/domain";
import"./styles.css";
const cats=[["all","Todos"],["dogs","Perros"],["cats","Gatos"],["birds","Aves"],["farm","Granja"],["accessories","Accesorios"]];
function App(){
 const[category,setCategory]=useState("all"),[query,setQuery]=useState(""),[cart,setCart]=useState<CartItem[]>([]),[selected,setSelected]=useState<Product|null>(null),[panel,setPanel]=useState<"none"|"cart"|"checkout"|"account"|"admin">("none"),[orders,setOrders]=useState<Order[]>([]);
 const filtered=useMemo(()=>demoProducts.filter(p=>(category==="all"||p.category===category)&&(p.name.toLowerCase().includes(query.toLowerCase())||p.description.toLowerCase().includes(query.toLowerCase()))),[category,query]);
 const add=(p:Product)=>setCart(c=>{const e=c.find(i=>i.product.id===p.id);return e?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]});
 const qty=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.product.id!==id?i:[{product:i.product,quantity:Math.max(0,i.quantity+d)}]).filter(i=>i.quantity>0));
 const total=cartTotal(cart),count=cart.reduce((s,i)=>s+i.quantity,0);
 const goHome=()=>{setSelected(null);setPanel("none")};
 return <div className="app">
 <header><div className="logo"onClick={goHome}><span>ANIMALIFE</span><small>PARAGUAY</small></div><div className="search"><Search size={18}/><input placeholder="¿Qué busca tu mascota?"value={query}onChange={e=>setQuery(e.target.value)}/></div><nav><button className="iconBtn"><Heart size={20}/></button><button className="account"onClick={()=>setPanel("account")}><UserCircle size={20}/> Cuenta</button><button className="cartBtn"onClick={()=>setPanel("cart")}><ShoppingCart size={20}/><b>{count}</b><span>Carrito</span></button></nav></header>
 <section className="hero"><div><p className="eyebrow">Cuidamos a quienes amas</p><h1>Todo para una vida<br/><em>más feliz</em> juntos.</h1><p className="sub">Productos seleccionados para perros, gatos, aves y animales de granja, con entrega en Paraguay.</p><button className="primary"onClick={()=>document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})}>Comprar ahora <ChevronRight size={18}/></button></div><div className="heroArt"><div className="petOrb">🐶</div><div className="leaf">🌿</div></div></section>
 <div className="benefits"><div><ShieldCheck/><span><b>Compra segura</b><small>Pagos preparados para proveedores locales</small></span></div><div><Truck/><span><b>Entrega rápida</b><small>Opciones de envío para Paraguay</small></span></div><div><Package/><span><b>Catálogo vivo</b><small>Nuevos productos y promociones</small></span></div></div>
 <main id="catalogo"><div className="sectionHead"><div><p className="eyebrow">Nuestra tienda</p><h2>Productos destacados</h2></div><button className="adminToggle"onClick={()=>setPanel("admin")}><Settings size={16}/> Administración</button></div><div className="tabs">{cats.map(([id,label])=><button key={id}className={category===id?"active":""}onClick={()=>setCategory(id)}>{label}</button>)}</div>
 <div className="grid">{filtered.map(p=><article key={p.id}className="card"><div className="imageWrap"onClick={()=>setSelected(p)}><img src={p.image}alt={p.name}/>{p.badge&&<span className="badge">{p.badge}</span>}<button className="heart"onClick={e=>{e.stopPropagation()}}><Heart size={17}/></button></div><div className="cardBody"><p className="cat">{p.category}</p><h3>{p.name}</h3><p className="desc">{p.description}</p><div className="buyRow"><strong>{formatGs(p.priceGs)}</strong><button onClick={()=>add(p)}><Plus size={18}/></button></div></div></article>)}</div></main>
 <footer><div><b>ANIMALIFE</b><span>Paraguay · Tu tienda para mascotas</span></div><div><span>Pagos locales preparados</span><span>Envíos y seguimiento preparados</span></div></footer>
 {selected&&<div className="overlay"onClick={()=>setSelected(null)}><div className="modal productModal"onClick={e=>e.stopPropagation()}><img src={selected.image}alt={selected.name}/><div><button className="close"onClick={()=>setSelected(null)}>×</button><p className="cat">{selected.category}</p><h2>{selected.name}</h2><p>{selected.description}</p><div className="bigPrice">{formatGs(selected.priceGs)}</div><div className="stock">{selected.stock} unidades disponibles</div><button className="primary full"onClick={()=>{add(selected);setSelected(null)}}>Añadir al carrito</button></div></div></div>}
 {panel==="cart"&&<div className="overlay"><div className="modal cartModal"><button className="close"onClick={()=>setPanel("none")}>×</button><h2>Tu carrito</h2>{!cart.length?<div className="empty">Aún no has añadido productos.</div>:<>{cart.map(i=><div className="cartLine"key={i.product.id}><img src={i.product.image}alt=""/><div><b>{i.product.name}</b><span>{formatGs(i.product.priceGs)}</span><div className="qty"><button onClick={()=>qty(i.product.id,-1)}><Minus size={14}/></button>{i.quantity}<button onClick={()=>qty(i.product.id,1)}><Plus size={14}/></button></div></div></div>)}<div className="total"><span>Total</span><b>{formatGs(total)}</b></div><button className="primary full"onClick={()=>setPanel("checkout")}>Continuar al checkout</button></>}</div></div>}
 {panel==="checkout"&&<div className="overlay"><div className="modal checkout"><button className="close"onClick={()=>setPanel("none")}>×</button><p className="eyebrow">Checkout</p><h2>Entrega en Paraguay</h2><p>Esta versión valida el flujo completo con proveedores simulados. No se realizan cobros reales.</p><label>Nombre<input id="co-name"placeholder="Tu nombre"/></label><label>Ciudad<input id="co-city"placeholder="Asunción"/></label><label>Dirección<input id="co-address"placeholder="Calle, número, referencia"/></label><div className="checkoutBox"><span>Envío demo</span><b>25.000 Gs · 1 día</b></div><div className="total"><span>Total</span><b>{formatGs(total+25000)}</b></div><button className="primary full"onClick={()=>{const id="ORD-"+Date.now().toString().slice(-6);setOrders(o=>[{id,customerId:"demo",items:cart,totalGs:total+25000,status:"pending",createdAt:new Date().toISOString(),shippingLabel:"Envío demo · 1 día"},...o]);setCart([]);setPanel("account")}}>Crear pedido demo</button></div></div>}
 {panel==="account"&&<div className="overlay"><div className="modal cartModal"><button className="close"onClick={()=>setPanel("none")}>×</button><p className="eyebrow">Mi cuenta</p><h2>Hola, cliente</h2><div className="accountCard"><UserCircle size={30}/><div><b>Cuenta demo</b><span>Preparada para Auth + perfiles reales.</span></div></div><h3>Pedidos</h3>{orders.length?orders.map(o=><div className="order"><div><b>{o.id}</b><span>{new Date(o.createdAt).toLocaleDateString("es-PY")}</span></div><strong>{formatGs(o.totalGs)}</strong><small>{o.status}</small></div>):<div className="empty">Todavía no hay pedidos.</div>}</div></div>}
 {panel==="admin"&&<div className="overlay"><div className="modal cartModal"><button className="close"onClick={()=>setPanel("none")}>×</button><p className="eyebrow">Back office</p><h2>Productos</h2><div className="adminPanel"><b>{demoProducts.length} productos</b><span>Catálogo demo · stock · precio · categoría</span><button className="secondary">+ Nuevo producto</button></div>{demoProducts.map(p=><div className="adminRow"><img src={p.image}alt=""/><div><b>{p.name}</b><span>{formatGs(p.priceGs)} · stock {p.stock}</span></div><button className="secondary">Editar</button></div>)}</div></div>}
 </div>
}
createRoot(document.getElementById("root")!).render(<App/>);