import React from "react";
import {SafeAreaView,View,Text,StyleSheet,Pressable,ScrollView} from "react-native";
import {StatusBar} from "expo-status-bar";
import {formatPYG} from "@animalife/shared";

export default function App(){
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><ScrollView><View style={s.header}><View><Text style={s.logo}>ANIMALIFE</Text><Text style={s.sub}>AGROVETERINARIA</Text></View><Pressable style={s.cart}><Text>🛒</Text></Pressable></View><View style={s.hero}><Text style={s.eyebrow}>ANIMALIFE PARAGUAY</Text><Text style={s.title}>Todo para el bienestar animal y el campo</Text><Text style={s.copy}>Productos veterinarios, alimentos y soluciones para cuidar a tus animales.</Text><Pressable style={s.button}><Text style={s.buttonText}>Ver catálogo</Text></Pressable></View><View style={s.trust}><Text>🚚 Envíos</Text><Text>✓ Compra segura</Text><Text>💬 WhatsApp</Text></View><View style={s.section}><Text style={s.sectionTitle}>Categorías</Text><View style={s.grid}>{["🐕 Perros","🐈 Gatos","🐄 Bovinos","🐎 Equinos","🌾 Campo","% Ofertas"].map(x=><View style={s.card} key={x}><Text style={s.cardText}>{x}</Text></View>)}</View></View><View style={s.section}><Text style={s.sectionTitle}>Compra segura en PYG</Text><Text style={s.copy}>Los precios se muestran en guaraníes paraguayos.</Text><Text style={s.price}>{formatPYG(669999)}</Text></View></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},header:{padding:18,borderBottomWidth:1,borderBottomColor:"#e6eee9",flexDirection:"row",alignItems:"center"},logo:{fontSize:20,fontWeight:"900",color:"#126b43"},sub:{fontSize:8,letterSpacing:2,color:"#71857c"},cart:{marginLeft:"auto"},hero:{backgroundColor:"#eaf5ed",padding:28},eyebrow:{fontSize:10,fontWeight:"800",color:"#3d8a62",letterSpacing:1.5},title:{fontSize:35,fontWeight:"900",color:"#123b2a",marginTop:12,lineHeight:38},copy:{fontSize:15,color:"#557065",lineHeight:23,marginTop:12},button:{backgroundColor:"#13804f",padding:14,borderRadius:9,marginTop:22,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"800"},trust:{flexDirection:"row",justifyContent:"space-around",padding:16,borderBottomWidth:1,borderBottomColor:"#e6eee9"},section:{padding:22},sectionTitle:{fontSize:24,fontWeight:"900",color:"#17342a",marginBottom:15},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{width:"31%",minHeight:75,borderWidth:1,borderColor:"#e1ebe5",borderRadius:12,alignItems:"center",justifyContent:"center",padding:8},cardText:{fontSize:12,fontWeight:"800",textAlign:"center"},price:{fontSize:26,fontWeight:"900",color:"#126b43",marginTop:10}});
