import React,{useMemo,useState} from "react";
import {SafeAreaView,View,Text,StyleSheet,Pressable,ScrollView,TextInput} from "react-native";
import {formatPYG} from "@animalife/shared";
const products=[{id:"1",name:"FINOTRATO PRIME",cat:"Perros",price:0,icon:"🐕",note:"Precio por confirmar"},{id:"2",name:"FLURALAB BOVINOS 5%",cat:"Bovinos",price:669999,icon:"🐄",note:"Stock por confirmar"},{id:"3",name:"RAGUIFE PRIME COMBO CRECIMIENTO",cat:"Perros",price:0,icon:"🐕",note:"Precio por confirmar"},{id:"4",name:"RANGER 75,7 SG",cat:"Campo",price:0,icon:"🌾",note:"Ficha por verificar"},{id:"5",name:"CIPERMETRINA 6% CALBOS",cat:"Campo",price:0,icon:"🌾",note:"Ficha por verificar"},{id:"6",name:"HIPOFEN PASTA ORAL 20g",cat:"Equinos",price:0,icon:"🐎",note:"Ficha por verificar"}];
export default function App(){
 const [screen,setScreen]=useState("home"),[query,setQuery]=useState(""),[cart,setCart]=useState<Record<string,number>>({});
 const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())),[query]);
 const add=(id:string)=>setCart(c=>({...c,[id]:(c[id]||0)+1})); const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=Object.entries(cart).reduce((sum,[id,q])=>sum+(products.find(p=>p.id===id)?.price||0)*q,0);
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>setScreen("home")}><Text style={s.logo}>ANIMALIFE</Text><Text style={s.sub}>AGROVETERINARIA</Text></Pressable><Pressable style={s.cart} onPress={()=>setScreen("cart")}><Text style={s.cartText}>🛒 {count}</Text></Pressable></View>
 {screen==="home"&&<ScrollView><View style={s.hero}><Text style={s.eyebrow}>ANIMALIFE PARAGUAY</Text><Text style={s.title}>Todo para el bienestar animal y el campo</Text><Text style={s.copy}>Productos veterinarios, alimentos y soluciones para cuidar a tus animales.</Text><Pressable style={s.button} onPress={()=>setScreen("catalog")}><Text style={s.buttonText}>Ver catálogo</Text></Pressable></View><View style={s.trust}><Text>🚚 Envíos</Text><Text>✓ Seguro</Text><Text>💬 WhatsApp</Text></View><View style={s.section}><Text style={s.sectionTitle}>Categorías</Text><View style={s.grid}>{["🐕 Perros","🐈 Gatos","🐄 Bovinos","🐎 Equinos","🌾 Campo","% Ofertas"].map(x=><Pressable onPress={()=>setScreen("catalog")} style={s.card} key={x}><Text style={s.cardText}>{x}</Text></Pressable>)}</View></View></ScrollView>}
 {screen==="catalog"&&<ScrollView style={s.body}><Text style={s.heading}>Catálogo</Text><TextInput value={query} onChangeText={setQuery} placeholder="Buscar productos..." style={s.input}/>{filtered.map(p=><View style={s.product} key={p.id}><View style={s.art}><Text style={s.artText}>{p.icon}</Text></View><View style={s.productCopy}><Text style={s.productName}>{p.name}</Text><Text style={s.muted}>{p.cat}</Text><Text style={s.price}>{p.price?formatPYG(p.price):p.note}</Text><Pressable style={s.smallButton} disabled={!p.price} onPress={()=>add(p.id)}><Text style={s.buttonText}>{p.price?"Agregar":"No disponible"}</Text></Pressable></View></View>)}</ScrollView>}
 {screen==="cart"&&<ScrollView style={s.body}><Text style={s.heading}>Carrito</Text>{count===0?<View style={s.empty}><Text style={s.headingSmall}>Tu carrito está vacío</Text><Pressable style={s.button} onPress={()=>setScreen("catalog")}><Text style={s.buttonText}>Ir al catálogo</Text></Pressable></View>:<>{Object.entries(cart).map(([id,q])=>{const p=products.find(x=>x.id===id)!;return <View style={s.row} key={id}><Text style={s.rowName}>{p.name}</Text><Text>× {q}</Text><Text>{p.price?formatPYG(p.price*q):"Por confirmar"}</Text></View>})}<View style={s.total}><Text>Total</Text><Text style={s.price}>{formatPYG(total)}</Text></View><View style={s.notice}><Text>El checkout real se conecta con Supabase y el proveedor de pago autorizado.</Text></View></>}</ScrollView>}
 {screen==="account"&&<ScrollView style={s.body}><Text style={s.heading}>Mi cuenta</Text><View style={s.empty}><Text style={s.headingSmall}>Cuenta Animalife</Text><Text style={s.copy}>Inicia sesión o crea una cuenta para consultar pedidos, direcciones y repetir compras.</Text><Pressable style={s.button}><Text style={s.buttonText}>Iniciar sesión</Text></Pressable></View></ScrollView>}
 <View style={s.tabs}><Pressable onPress={()=>setScreen("home")}><Text>Inicio</Text></Pressable><Pressable onPress={()=>setScreen("catalog")}><Text>Catálogo</Text></Pressable><Pressable onPress={()=>setScreen("cart")}><Text>🛒 Carrito</Text></Pressable><Pressable onPress={()=>setScreen("account")}><Text>Cuenta</Text></Pressable></View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},header:{padding:16,borderBottomWidth:1,borderBottomColor:"#e6eee9",flexDirection:"row",alignItems:"center"},logo:{fontSize:20,fontWeight:"900",color:"#126b43"},sub:{fontSize:8,letterSpacing:2,color:"#71857c"},cart:{marginLeft:"auto"},cartText:{fontWeight:"800",color:"#126b43"},body:{padding:18},hero:{backgroundColor:"#eaf5ed",padding:26},eyebrow:{fontSize:10,fontWeight:"800",color:"#3d8a62",letterSpacing:1.5},title:{fontSize:34,fontWeight:"900",color:"#123b2a",marginTop:12,lineHeight:38},copy:{fontSize:15,color:"#557065",lineHeight:23,marginTop:10},button:{backgroundColor:"#13804f",padding:14,borderRadius:9,marginTop:20,alignItems:"center"},smallButton:{backgroundColor:"#13804f",padding:10,borderRadius:8,alignItems:"center",marginTop:10},buttonText:{color:"#fff",fontWeight:"800"},trust:{flexDirection:"row",justifyContent:"space-around",padding:15,borderBottomWidth:1,borderBottomColor:"#e6eee9"},section:{padding:20},sectionTitle:{fontSize:24,fontWeight:"900",color:"#17342a",marginBottom:15},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{width:"31%",minHeight:75,borderWidth:1,borderColor:"#e1ebe5",borderRadius:12,alignItems:"center",justifyContent:"center",padding:8},cardText:{fontSize:12,fontWeight:"800",textAlign:"center"},tabs:{height:70,borderTopWidth:1,borderTopColor:"#e1ebe5",flexDirection:"row",justifyContent:"space-around",alignItems:"center"},heading:{fontSize:30,fontWeight:"900",marginBottom:15,color:"#17342a"},headingSmall:{fontSize:20,fontWeight:"900"},input:{borderWidth:1,borderColor:"#d3e0da",borderRadius:9,padding:12,marginBottom:15},product:{borderWidth:1,borderColor:"#e1ebe5",borderRadius:13,marginBottom:14,overflow:"hidden"},art:{height:150,backgroundColor:"#edf6ef",alignItems:"center",justifyContent:"center"},artText:{fontSize:70},productCopy:{padding:15},productName:{fontWeight:"900",fontSize:16},muted:{fontSize:12,color:"#71857c",marginTop:5},price:{fontWeight:"900",fontSize:18,color:"#126b43",marginTop:8},empty:{padding:25,borderWidth:1,borderColor:"#e1ebe5",borderRadius:13},row:{flexDirection:"row",gap:10,alignItems:"center",paddingVertical:14,borderBottomWidth:1,borderBottomColor:"#e7eee9"},rowName:{flex:1,fontWeight:"700"},total:{flexDirection:"row",justifyContent:"space-between",paddingVertical:20},notice:{backgroundColor:"#fff8e6",borderWidth:1,borderColor:"#eadcae",padding:14,borderRadius:9,marginTop:10}});
