"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "../../../lib/supabase-browser";
import SiteHeader from "../../../components/SiteHeader";
import SiteFooter from "../../../components/SiteFooter";
export default function AdminProducts(){const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
 async function load(){const s=createClient();if(!s){setMessage("Supabase no está configurado.");setLoading(false);return}const {data:{user}}=await s.auth.getUser();if(!user){setMessage("Inicia sesión como administrador.");setLoading(false);return}const {data:p}=await s.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="ADMIN"){setMessage("Acceso restringido.");setLoading(false);return}const {data,error}=await s.from("products").select("id,name,sku,brand,stock,low_stock_threshold,price_pyg,sale_price_pyg,verified,active").order("name");if(error)setMessage(error.message);else setRows(data??[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function update(id:string,patch:any){const s=createClient();if(!s)return;setMessage("Guardando…");const {error}=await s.from("products").update(patch).eq("id",id);if(error)setMessage(error.message);else{setMessage("Guardado.");await load()}}
 return <main><SiteHeader/><div className="container admin"><div className="breadcrumbs"><Link href="/admin">Admin</Link> / Productos</div><div className="admin-table-head"><div><span className="eyebrow">CATÁLOGO</span><h1>Productos</h1></div><Link className="btn btn-light" href="/admin">← Dashboard</Link></div>{message&&<p className="notice">{message}</p>}{loading?<div className="empty">Cargando…</div>:<div className="admin-table"><div className="admin-product-head"><span>Producto</span><span>Precio</span><span>Stock</span><span>Verificado</span><span>Activo</span></div>{rows.map(x=><div className="admin-product-row" key={x.id}><div><b>{x.name}</b><small>{x.brand||"Marca por confirmar"} · {x.sku}</small></div><span>Gs. {Number(x.sale_price_pyg??x.price_pyg).toLocaleString("es-PY")}</span><input aria-label={"Stock "+x.name} type="number" min="0" value={x.stock} onChange={e=>setRows(rs=>rs.map(r=>r.id===x.id?{...r,stock:Number(e.target.value)}:r))} onBlur={e=>update(x.id,{stock:Number(e.target.value)})}/><label className="switch"><input type="checkbox" checked={x.verified} onChange={e=>{setRows(rs=>rs.map(r=>r.id===x.id?{...r,verified:e.target.checked}:r));update(x.id,{verified:e.target.checked})}}/><span></span></label><label className="switch"><input type="checkbox" checked={x.active} onChange={e=>{setRows(rs=>rs.map(r=>r.id===x.id?{...r,active:e.target.checked}:r));update(x.id,{active:e.target.checked})}}/><span></span></label></div>)}</div>}</div><SiteFooter/></main>}