"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import type {Product} from "@animalife/shared";
import {formatPYG} from "@animalife/shared";
import type {CatalogCategory} from "../lib/catalog-server";
function Art({product}:{product:Product}){return <div className="product-art">{product.image?<img src={product.image} alt=""/>:<div className="product-placeholder">{product.animal==="BOVINOS"?"🐄":product.animal==="EQUINOS"?"🐎":product.animal==="CAMPO"?"🌿":product.animal==="GATOS"?"🐈":"🐕"}</div>}</div>}
export default function CatalogClient({products,categories,initialCategory="Todos",initialQuery=""}:{products:Product[];categories:CatalogCategory[];initialCategory?:string;initialQuery?:string}){
 const [query,setQuery]=useState(initialQuery);const [category,setCategory]=useState(initialCategory);const [sort,setSort]=useState("relevance");
 const filtered=useMemo(()=>{let list=products.filter(p=>(category==="Todos"||p.category===category||category==="Ofertas"&&p.salePrice));list=list.filter(p=>(p.name+" "+(p.brand??"")).toLowerCase().includes(query.toLowerCase()));if(sort==="price")list=[...list].sort((a,b)=>(a.salePrice??a.price)-(b.salePrice??b.price));return list},[products,category,query,sort]);
 return <main><header className="site-header"><div className="header-main container"><Link href="/" className="logo"><span className="logo-mark">A</span><span><b>ANIMALIFE</b><small>AGROVETERINARIA</small></span></Link><form className="search-bar" onSubmit={e=>e.preventDefault()}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué estás buscando?"/><button>⌕</button></form><nav className="header-tools"><Link href="/account" className="tool">♙ <small>Mi cuenta</small></Link><Link href="/cart" className="tool">🛒 <small>Carrito</small></Link></nav></div><nav className="category-nav"><div className="container category-inner">{categories.map(c=><Link key={c.slug} href={"/catalog?category="+encodeURIComponent(c.name)}><span>{c.icon}</span>{c.name}</Link>)}</div></nav></header>
 <div className="container breadcrumbs"><Link href="/">Inicio</Link> / Catálogo</div><div className="container catalog-shell"><div className="catalog-layout"><aside className="filters"><div className="filter-title">Filtrar productos</div><div className="filter-group"><h4>Categoría</h4><label className="filter-option"><span>Todos los productos</span><input type="radio" checked={category==="Todos"} onChange={()=>setCategory("Todos")}/></label>{categories.filter(c=>c.name!=="Ofertas").map(c=><label className="filter-option" key={c.slug}><span>{c.name}</span><input type="radio" checked={category===c.name} onChange={()=>setCategory(c.name)}/></label>)}</div><div className="filter-group"><h4>Disponibilidad</h4><label className="filter-option"><span>Disponible para compra</span><input type="checkbox"/></label></div><div className="filter-group"><h4>Marca</h4>{Array.from(new Set(products.map(p=>p.brand).filter(Boolean))).slice(0,5).map(b=><label className="filter-option" key={b}><span>{b}</span><input type="checkbox"/></label>)}</div></aside><section><div className="catalog-head"><div><span className="eyebrow">CATÁLOGO ANIMALIFE</span><h1>{category==="Todos"?"Todos los productos":category}</h1><p>{filtered.length} productos</p></div><select className="sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Ordenar: Relevancia</option><option value="price">Precio: menor a mayor</option></select></div>{!filtered.length?<div className="empty"><h2>Catálogo en preparación</h2><p>No hay productos que coincidan con tu búsqueda.</p></div>:<div className="product-grid">{filtered.map(p=><Link href={"/product/"+p.slug} className="product-card" key={p.id}><Art product={p}/><div className="product-info"><span className="tag">{p.verified&&p.stock>0?"Disponible":"Por verificar"}</span><h3>{p.name}</h3><small>{p.brand??p.category} · {p.packageSize??"Presentación por confirmar"}</small><strong>{p.price>0?formatPYG(p.salePrice??p.price):"Precio a confirmar"}</strong></div></Link>)}</div>}</section></div></div></main>;
}