-- Animalife Paraguay demo catalog fixture seed. These are test records, not real inventory.
-- All DEMO rows are unverified, have zero stock and must not be sold until manually verified.
-- Idempotent by SKU; does not modify non-demo products.
INSERT INTO public.categories (name, slug, active, sort_order)
VALUES ('Veterinaria','veterinaria',true,6)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name,active=true,sort_order=6;

INSERT INTO public.products (sku,slug,name,brand,category_id,animal,description,package_size,price_pyg,stock,image_path,verified,regulated,requires_prescription,featured,active)
VALUES
('DEMO-CAT-01','demo-alimento-gato-adulto','Alimento Gato Adulto','Michi Select',(SELECT id FROM public.categories WHERE slug='gatos'),'GATOS','Alimento de demostración para gatos adultos. Confirmar composición y peso neto.','7.5 kg',145000,0,'https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-CAT-02','demo-alimento-para-gatitos','Alimento para Gatitos','Michi Select',(SELECT id FROM public.categories WHERE slug='gatos'),'GATOS','Nutrición ilustrativa para gatitos durante su crecimiento. Verificar etapa recomendada.','3 kg',168000,0,'https://images.pexels.com/photos/127028/pexels-photo-127028.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-CAT-03','demo-arena-sanitaria-aglomerante','Arena Sanitaria Aglomerante','CleanPaws',(SELECT id FROM public.categories WHERE slug='gatos'),'GATOS','Arena para facilitar la limpieza diaria del arenero. Presentación ilustrativa.','10 kg',68000,0,'https://images.pexels.com/photos/320014/pexels-photo-320014.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-CAT-04','demo-rascador-compacto','Rascador Compacto','Casa Gato',(SELECT id FROM public.categories WHERE slug='gatos'),'GATOS','Rascador para juego y cuidado de uñas dentro del hogar.','1 unidad',125000,0,'https://images.pexels.com/photos/45201/pexels-photo-45201.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-CAT-05','demo-juguete-interactivo','Juguete Interactivo','PlayPet',(SELECT id FROM public.categories WHERE slug='gatos'),'GATOS','Juguete de estimulación para enriquecer el entorno del gato.','1 unidad',35000,0,'https://images.pexels.com/photos/1056251/pexels-photo-1056251.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-CAT-06','demo-transportadora-ventilada','Transportadora Ventilada','MovePet',(SELECT id FROM public.categories WHERE slug='gatos'),'GATOS','Transportadora para traslados. Confirmar medidas y capacidad antes de usar.','1 unidad',195000,0,'https://images.pexels.com/photos/156934/pexels-photo-156934.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-COW-01','demo-suplemento-mineral','Suplemento Mineral','CampoForte',(SELECT id FROM public.categories WHERE slug='bovinos'),'BOVINOS','Producto de muestra para catálogo. Composición, especie objetivo y dosis requieren validación profesional.','25 kg',245000,0,'https://images.pexels.com/photos/422218/pexels-photo-422218.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-COW-02','demo-balde-de-alimentacion','Balde de Alimentación','RuralPro',(SELECT id FROM public.categories WHERE slug='bovinos'),'BOVINOS','Accesorio resistente para alimentación en finca. Capacidad ilustrativa.','20 L',89000,0,'https://images.pexels.com/photos/422202/pexels-photo-422202.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-COW-03','demo-guantes-veterinarios','Guantes Veterinarios','VetPro',(SELECT id FROM public.categories WHERE slug='bovinos'),'BOVINOS','Guantes para procedimientos de manejo. Elegir material y talla apropiados.','100 unidades',39000,0,'https://images.pexels.com/photos/162240/pexels-photo-162240.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-COW-04','demo-bebedero-de-campo','Bebedero de Campo','AgroVida',(SELECT id FROM public.categories WHERE slug='bovinos'),'BOVINOS','Bebedero de uso rural. Verificar materiales, capacidad e instalación.','1 unidad',310000,0,'https://images.pexels.com/photos/144248/pexels-photo-144248.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-COW-05','demo-kit-de-identificacion','Kit de Identificación','RodeoTag',(SELECT id FROM public.categories WHERE slug='bovinos'),'BOVINOS','Kit de muestra para gestión de animales. Confirmar normativa y especificaciones locales.','10 unidades',65000,0,'https://images.pexels.com/photos/735968/pexels-photo-735968.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-COW-06','demo-cepillo-ganadero','Cepillo Ganadero','CampoForte',(SELECT id FROM public.categories WHERE slug='bovinos'),'BOVINOS','Cepillo para limpieza y manejo rutinario del ganado.','1 unidad',115000,0,'https://images.pexels.com/photos/162284/pexels-photo-162284.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-DOG-01','demo-alimento-adulto-premium','Alimento Adulto Premium','Animalife Select',(SELECT id FROM public.categories WHERE slug='perros'),'PERROS','Alimento completo de demostración para perros adultos. Confirmar fórmula, peso neto y ración antes de publicar.','15 kg',185000,0,'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-DOG-02','demo-alimento-para-cachorros','Alimento para Cachorros','CanPro',(SELECT id FROM public.categories WHERE slug='perros'),'PERROS','Nutrición ilustrativa para cachorros en crecimiento. La etapa y la ración deben verificarse en etiqueta.','10 kg',210000,0,'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-DOG-03','demo-snacks-de-entrenamiento','Snacks de Entrenamiento','Bark&Go',(SELECT id FROM public.categories WHERE slug='perros'),'PERROS','Premios para reforzar hábitos positivos y sesiones de entrenamiento.','200 g',42000,0,'https://images.pexels.com/photos/4587998/pexels-photo-4587998.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-DOG-04','demo-correa-urbana-reforzada','Correa Urbana Reforzada','Vida Pet',(SELECT id FROM public.categories WHERE slug='perros'),'PERROS','Correa resistente para paseos diarios. Talla y longitud ilustrativas.','1 unidad',78000,0,'https://images.pexels.com/photos/5731866/pexels-photo-5731866.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-DOG-05','demo-shampoo-piel-sensible','Shampoo Piel Sensible','VetCare',(SELECT id FROM public.categories WHERE slug='perros'),'PERROS','Producto de higiene ilustrativo. Revisar ingredientes y compatibilidad con cada animal.','250 ml',56000,0,'https://images.pexels.com/photos/6568945/pexels-photo-6568945.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-DOG-06','demo-cama-confort-mediana','Cama Confort Mediana','Hogar Pet',(SELECT id FROM public.categories WHERE slug='perros'),'PERROS','Cama acolchada para descanso en interiores. Medidas ilustrativas.','1 unidad',165000,0,'https://images.pexels.com/photos/7210747/pexels-photo-7210747.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-FLD-01','demo-manguera-reforzada-20-m','Manguera Reforzada 20 m','AgroForte',(SELECT id FROM public.categories WHERE slug='campo'),'CAMPO','Manguera para tareas generales de campo. Longitud y materiales de demostración.','20 m',185000,0,'https://images.pexels.com/photos/2132171/pexels-photo-2132171.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-FLD-02','demo-pulverizador-manual','Pulverizador Manual','AgroForte',(SELECT id FROM public.categories WHERE slug='campo'),'CAMPO','Pulverizador para usos permitidos conforme a etiqueta y normativa local.','5 L',97000,0,'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-FLD-03','demo-guantes-de-trabajo','Guantes de Trabajo','RuralPro',(SELECT id FROM public.categories WHERE slug='campo'),'CAMPO','Guantes para tareas de mantenimiento rural. Tallas ilustrativas.','1 par',45000,0,'https://images.pexels.com/photos/1586298/pexels-photo-1586298.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-FLD-04','demo-tijera-de-poda','Tijera de Poda','CampoForte',(SELECT id FROM public.categories WHERE slug='campo'),'CAMPO','Tijera para poda y mantenimiento de plantas.','1 unidad',88000,0,'https://images.pexels.com/photos/4503269/pexels-photo-4503269.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-FLD-05','demo-linterna-recargable','Linterna Recargable','RuralPro',(SELECT id FROM public.categories WHERE slug='campo'),'CAMPO','Linterna recargable para tareas con baja iluminación.','1 unidad',125000,0,'https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-FLD-06','demo-botas-de-trabajo','Botas de Trabajo','CampoForte',(SELECT id FROM public.categories WHERE slug='campo'),'CAMPO','Calzado de trabajo para tareas rurales. Verificar talles disponibles.','1 par',225000,0,'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-HOR-01','demo-cepillo-para-crin','Cepillo para Crin','EquiCare',(SELECT id FROM public.categories WHERE slug='equinos'),'EQUINOS','Cepillo de cuidado diario para crin y cola. Especificaciones ilustrativas.','1 unidad',62000,0,'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-HOR-02','demo-cabestro-ajustable','Cabestro Ajustable','EquiCare',(SELECT id FROM public.categories WHERE slug='equinos'),'EQUINOS','Cabestro para manejo cotidiano. Elegir talla apropiada para el caballo.','1 unidad',145000,0,'https://images.pexels.com/photos/635499/pexels-photo-635499.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-HOR-03','demo-manta-liviana','Manta Liviana','HorseField',(SELECT id FROM public.categories WHERE slug='equinos'),'EQUINOS','Manta para establo y transporte. Revisar medidas del caballo.','1 unidad',390000,0,'https://images.pexels.com/photos/1996335/pexels-photo-1996335.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-HOR-04','demo-kit-de-limpieza-equina','Kit de Limpieza Equina','StablePro',(SELECT id FROM public.categories WHERE slug='equinos'),'EQUINOS','Kit de muestra para cuidado exterior del caballo.','1 kit',185000,0,'https://images.pexels.com/photos/52500/pexels-photo-52500.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-HOR-05','demo-balde-de-establo','Balde de Establo','StablePro',(SELECT id FROM public.categories WHERE slug='equinos'),'EQUINOS','Balde resistente para uso en establo. Capacidad ilustrativa.','15 L',78000,0,'https://images.pexels.com/photos/162389/pexels-photo-162389.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-HOR-06','demo-bolsa-para-premios','Bolsa para Premios','EquiCare',(SELECT id FROM public.categories WHERE slug='equinos'),'EQUINOS','Bolsa práctica para guardar premios durante el entrenamiento.','1 unidad',49000,0,'https://images.pexels.com/photos/52518/pexels-photo-52518.jpeg?auto=compress&cs=tinysrgb&w=900',false,false,false,false,true),
('DEMO-VET-01','demo-gasas-esteriles','Gasas Estériles','VetPro',(SELECT id FROM public.categories WHERE slug='veterinaria'),'VETERINARIA','Insumo ilustrativo para uso profesional. Verificar esterilidad y presentación del paquete.','100 unidades',18000,0,'https://images.pexels.com/photos/6235233/pexels-photo-6235233.jpeg?auto=compress&cs=tinysrgb&w=900',false,true,false,false,true),
('DEMO-VET-02','demo-venda-cohesiva','Venda Cohesiva','VetPro',(SELECT id FROM public.categories WHERE slug='veterinaria'),'VETERINARIA','Venda para uso veterinario según indicación profesional.','1 unidad',22000,0,'https://images.pexels.com/photos/6235235/pexels-photo-6235235.jpeg?auto=compress&cs=tinysrgb&w=900',false,true,false,false,true),
('DEMO-VET-03','demo-termometro-digital','Termómetro Digital','MedAnimal',(SELECT id FROM public.categories WHERE slug='veterinaria'),'VETERINARIA','Termómetro digital para controles veterinarios; seguir instrucciones del fabricante.','1 unidad',65000,0,'https://images.pexels.com/photos/6235237/pexels-photo-6235237.jpeg?auto=compress&cs=tinysrgb&w=900',false,true,false,false,true),
('DEMO-VET-04','demo-jeringas-desechables','Jeringas Desechables','MedAnimal',(SELECT id FROM public.categories WHERE slug='veterinaria'),'VETERINARIA','Jeringas de un solo uso. Elegir volumen correcto y desechar de forma segura.','10 unidades',12000,0,'https://images.pexels.com/photos/6235239/pexels-photo-6235239.jpeg?auto=compress&cs=tinysrgb&w=900',false,true,false,false,true),
('DEMO-VET-05','demo-antiseptico-de-uso-externo','Antiséptico de Uso Externo','VetCare',(SELECT id FROM public.categories WHERE slug='veterinaria'),'VETERINARIA','Producto de demostración. Confirmar especie, indicación y uso con un veterinario.','250 ml',48000,0,'https://images.pexels.com/photos/6235241/pexels-photo-6235241.jpeg?auto=compress&cs=tinysrgb&w=900',false,true,false,false,true),
('DEMO-VET-06','demo-botiquin-veterinario','Botiquín Veterinario','VetPro',(SELECT id FROM public.categories WHERE slug='veterinaria'),'VETERINARIA','Organizador para insumos básicos. El contenido del kit es ilustrativo.','1 kit',245000,0,'https://images.pexels.com/photos/6235243/pexels-photo-6235243.jpeg?auto=compress&cs=tinysrgb&w=900',false,true,false,false,true)
ON CONFLICT (sku) DO UPDATE SET slug=EXCLUDED.slug,name=EXCLUDED.name,brand=EXCLUDED.brand,
 category_id=EXCLUDED.category_id,animal=EXCLUDED.animal,description=EXCLUDED.description,
 package_size=EXCLUDED.package_size,price_pyg=EXCLUDED.price_pyg,stock=0,image_path=EXCLUDED.image_path,
 verified=false,regulated=EXCLUDED.regulated,requires_prescription=false,featured=false,active=true;
