"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
export default function Account(){
 const [mode,setMode]=useState<"login"|"signup">("login");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [message,setMessage]=useState("");const [user,setUser]=useState<any>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{const s=createClient();if(!s){setLoading(false);return}s.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const {data}=s.auth.onAuthStateChange((_e,session)=>setUser(session?.user??null));return()=>data.subscription.unsubscribe()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");const s=createClient();if(!s){setMessage("Supabase no está configurado.");return}if(mode==="signup"){const {error}=await s.auth.signUp({email,password,options:{data:{full_name:name}}});setMessage(error?.message??"Cuenta creada. Revisa tu email si la confirmación está activada.");}else{const {error}=await s.auth.signInWithPassword({email,password});setMessage(error?.message??"Sesión iniciada.");}}
 async function logout(){const s=createClient();await s?.auth.signOut();setUser(null)}
 if(loading)return <main><SiteHeader/><div className="container checkout-page"><div className="empty">Cargando cuenta…</div></div><SiteFooter/></main>;
 return <main><SiteHeader/><div className="container account-page">{user?<><span className="eyebrow">MI CUENTA</span><h1 className="page-title">Bienvenido</h1><div className="account-grid"><div className="account-card"><span className="account-avatar">{(user.email?.[0]||"A").toUpperCase()}</span><h2>{user.user_metadata?.full_name||user.email}</h2><p>{user.email}</p><button className="btn btn-green" onClick={logout}>Cerrar sesión</button></div><div className="account-card"><h2>Mis pedidos</h2><p>Consulta aquí tus pedidos, estados de pago y entregas.</p><Link className="btn btn-light account-link" href="/catalog">Seguir comprando →</Link></div><div className="account-card"><h2>Direcciones</h2><p>Guarda tus direcciones de entrega para futuras compras.</p></div></div></>:<div className="auth-shell"><div className="auth-copy"><span className="eyebrow">ANIMALIFE · PARAGUAY</span><h1>{mode==="login"?"Bienvenido de nuevo.":"Crea tu cuenta."}</h1><p>Compra de forma sencilla y consulta tus pedidos y entregas desde un solo lugar.</p><Link href="/catalog" className="btn btn-lime">Explorar catálogo</Link></div><form className="form-card auth-card" onSubmit={submit}><h2>{mode==="login"?"Iniciar sesión":"Crear cuenta"}</h2>{mode==="signup"&&<label>Nombre completo<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label><button className="btn btn-green" style={{width:"100%"}}>{mode==="login"?"Entrar":"Crear cuenta"}</button>{message&&<p className="notice">{message}</p>}<button type="button" className="link-button auth-switch" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"¿No tienes cuenta? Crear una":"Ya tengo una cuenta"}</button></form></div>}</div><SiteFooter/></main>
}