"use client";
import Link from "next/link";
import {useState} from "react";
import {createClient} from "../../lib/supabase-browser";
export default function Account(){
 const [mode,setMode]=useState<"login"|"signup">("login"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [message,setMessage]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");const supabase=createClient();if(!supabase){setMessage("Supabase todavía no está configurado.");return} if(mode==="signup"){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});setMessage(error?.message??"Cuenta creada. Revisa tu email si la confirmación está activada.");}else{const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message??"Sesión iniciada.");}}
 return <main><header className="site-header"><div className="header-top container"><Link className="brand" href="/">ANIMALIFE <small>AGROVETERINARIA</small></Link><Link href="/">Inicio</Link></div></header><div className="container checkout-page"><span className="eyebrow">MI CUENTA</span><h1>{mode==="login"?"Iniciar sesión":"Crear cuenta"}</h1><form className="form-card narrow" onSubmit={submit}>{mode==="signup"&&<label>Nombre completo<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label><button className="button primary wide" type="submit">{mode==="login"?"Entrar":"Crear cuenta"}</button>{message&&<p className="notice">{message}</p>}<button type="button" className="link-button" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"¿No tienes cuenta? Crear una":"Ya tengo una cuenta"}</button></form></div></main>
}
